version: 2

models:
  - name: users
    description: "Table containing user information."
    columns:
      - name: id
        description: "Primary key for the user."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User's first name."
        tests:
          - not_null
      - name: last_name
        description: "User's last name."
        tests:
          - not_null
      - name: email
        description: "Email address of the user."
        tests:
          - unique
          - not_null
      - name: date_of_birth
        description: "User's date of birth."

  - name: films
    description: "Table containing movie details."
    columns:
      - name: film_id
        description: "Primary key for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Date when the film was released."
      - name: price
        description: "Ticket price for the film."
        tests:
          - not_null
      - name: rating
        description: "MPAA rating of the film."
      - name: user_rating
        description: "User-assigned rating between 1 and 5."
        tests:
          - not_null

  - name: film_category
    description: "Associates films with their categories."
    columns:
      - name: category_id
        description: "Primary key for the film category."
        tests:
          - unique
          - not_null
      - name: film_id
        description: "Foreign key referencing films.film_id."
        tests:
          - not_null
      - name: category_name
        description: "Name of the category."
        tests:
          - not_null

  - name: actors
    description: "Table containing actor names."
    columns:
      - name: actor_id
        description: "Primary key for the actor."
        tests:
          - unique
          - not_null
      - name: actor_name
        description: "Name of the actor."
        tests:
          - not_null

  - name: film_actors
    description: "Associative table linking actors and films."
    columns:
      - name: film_id
        description: "Foreign key referencing films.film_id."
        tests:
          - not_null
      - name: actor_id
        description: "Foreign key referencing actors.actor_id."
        tests:
          - not_null
          
  - name: film_ratings
    description: "Model that categorizes films based on user ratings and aggregates actors."
    columns:
      - name: film_id
        description: "Unique identifier of the film."
        tests:
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
      - name: price
        description: "Price of the film."
      - name: rating
        description: "MPAA rating of the film."
      - name: user_rating
        description: "Numerical rating given by users."
      - name: rating_category
        description: "Rating bucket generated from user_rating."
      - name: actors
        description: "List of associated actors."
